### ISSUE TITLE
require phash/audio throw an error

### ISSUE THREAD

**Issue by rubyrailsninja** [toy/pHash#15]
hello,
thank you for your great work about this gem :)

I would like to try it but when I required audio, an error occurs and I didn't find any help on google :/
any ideas ?

```
2.2.5 :001 > require 'phash/audio'
FFI::NotFoundError: Function 'ph_readaudio' not found in [libpHash.so]
	from /usr/local/rvm/gems/ruby-2.2.5/gems/ffi-1.9.25/lib/ffi/library.rb:273:in `attach_function'
	from /usr/local/rvm/gems/ruby-2.2.5/gems/pHash-1.2.1/lib/phash/audio.rb:17:in `<module:Phash>'
	from /usr/local/rvm/gems/ruby-2.2.5/gems/pHash-1.2.1/lib/phash/audio.rb:3:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from (irb):1
	from /usr/local/rvm/rubies/ruby-2.2.5/bin/irb:11:in `<main>'
2.2.5 :002 > 
```
thanks :)
Julien

**Comment by toy** [comment]
Hello Julien
My first guess is that you are using unpatched version of pHash which doesn't expose all the required functions for audio hashing. Have a look at https://github.com/toy/pHash-lib

**Comment by toy** [comment]
Archiving the repo
