### ISSUE TITLE
Could not open library libpHash.dylib

### ISSUE THREAD

**Issue by faustoct** [toy/pHash#18]
````
padrino c -e development
[tunemygc] not enabled
Traceback (most recent call last):
	21: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	20: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	19: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `<main>'
	18: from /Users/fausto/.rvm/gems/ruby-2.5.1/bin/padrino:23:in `load'
	17: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/bin/padrino:9:in `<top (required)>'
	16: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	15: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	14: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	13: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	12: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/lib/padrino-core/cli/base.rb:31:in `console'
	11: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/padrino-core-0.14.2/lib/padrino-core/cli/base.rb:31:in `require'
	10: from /Users/fausto/Projects/coding/viby-backend/config/boot.rb:12:in `<top (required)>'
	 9: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	 8: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	 7: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	 6: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	 5: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	 4: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	 3: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `require'
	 2: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/pHash-1.2.2/lib/pHash.rb:3:in `<top (required)>'
	 1: from /Users/fausto/.rvm/gems/ruby-2.5.1/gems/pHash-1.2.2/lib/pHash.rb:63:in `<module:Phash>'
/Users/fausto/.rvm/gems/ruby-2.5.1/gems/pHash-1.2.2/lib/pHash.rb:66:in `rescue in <module:Phash>': Specify path to pHash library using PHASH_LIB environment variable. Could not open library 'pHash': dlopen(pHash, 5): image not found. (LoadError)
Could not open library 'libpHash.dylib': dlopen(libpHash.dylib, 5): image not found
````

**Comment by toy** [comment]
The `libpHash.dylib` should be either in one of default lib paths (according to ffi) or as exception states you need to `Specify path to pHash library using PHASH_LIB environment variable`

**Comment by faustoct** [comment]
I'll give a try.
@toy is that easy to deploy and use it on heroku?

**Comment by toy** [comment]
To get it on heroku you need a compiled pHash there, I don't know if it is available from the package manager, but you can always compile from source. On linux it will be probably `libpHash.so`

**Comment by toy** [comment]
Archiving the repo
